// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlQN1ut0Ddda52FygjvB-CRPK0Z6OgTJc',
    appId: '1:1034896118654:web:71ec09b12fa97a6141192f',
    messagingSenderId: '1034896118654',
    projectId: 'dermpix-14695',
    authDomain: 'dermpix-14695.firebaseapp.com',
    storageBucket: 'dermpix-14695.firebasestorage.app',
    measurementId: 'G-QKR7H4XWSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4PQPH9LuXAyFSY_HpIUBHj7yL5S71vxY',
    appId: '1:1034896118654:android:83250d26a5677f4341192f',
    messagingSenderId: '1034896118654',
    projectId: 'dermpix-14695',
    storageBucket: 'dermpix-14695.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-G4UqS9KRsuWrmiWR6X_QVAjkIC40Qys',
    appId: '1:1034896118654:ios:d402fb267ac0be5b41192f',
    messagingSenderId: '1034896118654',
    projectId: 'dermpix-14695',
    storageBucket: 'dermpix-14695.firebasestorage.app',
    iosBundleId: 'com.example.dermPix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-G4UqS9KRsuWrmiWR6X_QVAjkIC40Qys',
    appId: '1:1034896118654:ios:d402fb267ac0be5b41192f',
    messagingSenderId: '1034896118654',
    projectId: 'dermpix-14695',
    storageBucket: 'dermpix-14695.firebasestorage.app',
    iosBundleId: 'com.example.dermPix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlQN1ut0Ddda52FygjvB-CRPK0Z6OgTJc',
    appId: '1:1034896118654:web:33cee4cfeb738f2541192f',
    messagingSenderId: '1034896118654',
    projectId: 'dermpix-14695',
    authDomain: 'dermpix-14695.firebaseapp.com',
    storageBucket: 'dermpix-14695.firebasestorage.app',
    measurementId: 'G-2Q7RJQJGH2',
  );
}
