import 'package:flutter/material.dart';
import 'package:camera/camera.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'app/app.dart';
import 'firebase_options.dart';  // auto-generated by FlutterFire

late List<CameraDescription> cameras;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  cameras = await availableCameras();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

   await Supabase.initialize(
    url: 'https://yzwqnakoukelmhpvcyaj.supabase.co', // your project URL
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6d3FuYWtvdWtlbG1ocHZjeWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzMDIyNjIsImV4cCI6MjA4MTg3ODI2Mn0.oQqefTrqO_6y-LYBy0i1PoaXR_q27ZQHBo6dMD8lbWk',
  );

  runApp(const DermPixApp());
}

